# Generated by Django 6.1.1 on 2026-09-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaauditor',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaauditor',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='documentogenerado',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='documentogenerado',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='accionmejoramiento',
            name='hallazgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.hallazgo'),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='informe',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacionalerta',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.accionmejoramiento'),
        ),
        migrations.AddField(
            model_name='notificacionalerta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='planauditoria',
            name='auditoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='cronogramaactividad',
            name='plan_auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.planauditoria'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='auditoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='accionmejoramiento',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.planmejoramiento'),
        ),
        migrations.AddField(
            model_name='seguimientoaccion',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.accionmejoramiento'),
        ),
        migrations.AddField(
            model_name='seguimientoaccion',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='unidad_auditada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.unidadauditada'),
        ),
    ]
