# Generated by Django 6.1.1 on 2026-09-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CronogramaActividad',
            new_name='CronogramaActividades',
        ),
    ]
