# Generated by Django 6.1.1 on 2026-09-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_grupo_director(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Director")


def eliminar_grupo_director(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Director").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auditorias", "0003_rename_cronogramaactividad_cronogramaactividades"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente de revisión", "Pendiente de revisión"),
                    ("Requiere correcciones", "Requiere correcciones"),
                    ("Aprobado", "Aprobado"),
                ],
                default="Pendiente de revisión",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="informe",
            name="fecha_revision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="informe",
            name="observaciones_revision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="informe",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(crear_grupo_director, eliminar_grupo_director),
    ]
